version = 1
SPDX-PackageName = "maintenance-operator"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/maintenance-operator"

[[annotations]]
path = [
    ".devcontainer/**",
    ".github/**",
    ".gitignore",
    ".dockerignore",
    ".golangci.yml",
    ".tiltignore",
    "CODEOWNERS",
    "Dockerfile",
    "Makefile",
    "PROJECT",
    "config/**",
    "dist/**",
    "examples/**",
    "go.mod",
    "go.sum",
    "REUSE.toml",
    "hack/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
