//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedInterface) DeepCopyInto(out *ExpectedInterface) {
	*out = *in
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]ExpectedNeighbor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedInterface.
func (in *ExpectedInterface) DeepCopy() *ExpectedInterface {
	if in == nil {
		return nil
	}
	out := new(ExpectedInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedNeighbor) DeepCopyInto(out *ExpectedNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedNeighbor.
func (in *ExpectedNeighbor) DeepCopy() *ExpectedNeighbor {
	if in == nil {
		return nil
	}
	out := new(ExpectedNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedNetworkSpec) DeepCopyInto(out *ExpectedNetworkSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]ExpectedInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedNetworkSpec.
func (in *ExpectedNetworkSpec) DeepCopy() *ExpectedNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ExpectedNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceMismatch) DeepCopyInto(out *InterfaceMismatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceMismatch.
func (in *InterfaceMismatch) DeepCopy() *InterfaceMismatch {
	if in == nil {
		return nil
	}
	out := new(InterfaceMismatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCheck) DeepCopyInto(out *ServerCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCheck.
func (in *ServerCheck) DeepCopy() *ServerCheck {
	if in == nil {
		return nil
	}
	out := new(ServerCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCheckList) DeepCopyInto(out *ServerCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCheckList.
func (in *ServerCheckList) DeepCopy() *ServerCheckList {
	if in == nil {
		return nil
	}
	out := new(ServerCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCheckSpec) DeepCopyInto(out *ServerCheckSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCheckSpec.
func (in *ServerCheckSpec) DeepCopy() *ServerCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ServerCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCheckStatus) DeepCopyInto(out *ServerCheckStatus) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]ServerReadinessStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCheckStatus.
func (in *ServerCheckStatus) DeepCopy() *ServerCheckStatus {
	if in == nil {
		return nil
	}
	out := new(ServerCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerReadinessStatus) DeepCopyInto(out *ServerReadinessStatus) {
	*out = *in
	if in.Mismatches != nil {
		in, out := &in.Mismatches, &out.Mismatches
		*out = make([]InterfaceMismatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerReadinessStatus.
func (in *ServerReadinessStatus) DeepCopy() *ServerReadinessStatus {
	if in == nil {
		return nil
	}
	out := new(ServerReadinessStatus)
	in.DeepCopyInto(out)
	return out
}
