//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedInterface) DeepCopyInto(out *ExpectedInterface) {
	*out = *in
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]ExpectedNeighbor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedInterface.
func (in *ExpectedInterface) DeepCopy() *ExpectedInterface {
	if in == nil {
		return nil
	}
	out := new(ExpectedInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedNeighbor) DeepCopyInto(out *ExpectedNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedNeighbor.
func (in *ExpectedNeighbor) DeepCopy() *ExpectedNeighbor {
	if in == nil {
		return nil
	}
	out := new(ExpectedNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedNetworkSpec) DeepCopyInto(out *ExpectedNetworkSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]ExpectedInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedNetworkSpec.
func (in *ExpectedNetworkSpec) DeepCopy() *ExpectedNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ExpectedNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceMismatch) DeepCopyInto(out *InterfaceMismatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceMismatch.
func (in *InterfaceMismatch) DeepCopy() *InterfaceMismatch {
	if in == nil {
		return nil
	}
	out := new(InterfaceMismatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWiringCheck) DeepCopyInto(out *NetworkWiringCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWiringCheck.
func (in *NetworkWiringCheck) DeepCopy() *NetworkWiringCheck {
	if in == nil {
		return nil
	}
	out := new(NetworkWiringCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkWiringCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWiringCheckList) DeepCopyInto(out *NetworkWiringCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkWiringCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWiringCheckList.
func (in *NetworkWiringCheckList) DeepCopy() *NetworkWiringCheckList {
	if in == nil {
		return nil
	}
	out := new(NetworkWiringCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkWiringCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWiringCheckSpec) DeepCopyInto(out *NetworkWiringCheckSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWiringCheckSpec.
func (in *NetworkWiringCheckSpec) DeepCopy() *NetworkWiringCheckSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkWiringCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkWiringCheckStatus) DeepCopyInto(out *NetworkWiringCheckStatus) {
	*out = *in
	if in.Mismatches != nil {
		in, out := &in.Mismatches, &out.Mismatches
		*out = make([]InterfaceMismatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkWiringCheckStatus.
func (in *NetworkWiringCheckStatus) DeepCopy() *NetworkWiringCheckStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkWiringCheckStatus)
	in.DeepCopyInto(out)
	return out
}
