---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - consoles
  - maintenanceplanruns
  - maintenanceplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - consoles/finalizers
  - maintenanceplanruns/finalizers
  - maintenanceplans/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - consoles/status
  - maintenanceplanruns/status
  - maintenanceplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - biossettings
  - biosversions
  - bmcsettings
  - bmcversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs
  - bmcsecrets
  - servers
  verbs:
  - get
  - list
  - watch
