---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - firmware.maintenance.ironcore.dev
  resources:
  - dellfirmwareupdateomes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - firmware.maintenance.ironcore.dev
  resources:
  - dellfirmwareupdateomes/finalizers
  verbs:
  - update
- apiGroups:
  - firmware.maintenance.ironcore.dev
  resources:
  - dellfirmwareupdateomes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
