apiVersion: baseboard.metal.ironcore.dev/v1alpha1
kind: BMCUserSet
metadata:
  name: bmcuserset-sample
spec:
  serverSelector:
    matchLabels:
      metal.ironcore.dev/Manufacturer: Dell
  template:
    userName: ops-admin
    roleID: Administrator
    rotationPeriod: 720h
