apiVersion: console.maintenance.metal.ironcore.dev/v1alpha1
kind: ServerManagementConsole
metadata:
  labels:
    app.kubernetes.io/name: maintenance-operator
    app.kubernetes.io/managed-by: kustomize
  name: servermanagementconsole-sample
spec:
  # TODO(user): Add fields here
