## Append samples of your project ##
resources:
- vendorconsole_v1alpha1_console.yaml
- readiness_v1alpha1_serverwiring.yaml
- vendorconsole_v1alpha1_firmwareupdatelenovo.yaml
- lenovoLXCASecret.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
