apiVersion: v1
kind: Secret
metadata:
  name: lenovo-lxca-credentials
  labels:
    app.kubernetes.io/name: metal-maintenance-operator
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  username: USERID
  password: PASSW0RD
