//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagement) DeepCopyInto(out *ServerManagement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagement.
func (in *ServerManagement) DeepCopy() *ServerManagement {
	if in == nil {
		return nil
	}
	out := new(ServerManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerManagement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementList) DeepCopyInto(out *ServerManagementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerManagement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementList.
func (in *ServerManagementList) DeepCopy() *ServerManagementList {
	if in == nil {
		return nil
	}
	out := new(ServerManagementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerManagementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementSpec) DeepCopyInto(out *ServerManagementSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementSpec.
func (in *ServerManagementSpec) DeepCopy() *ServerManagementSpec {
	if in == nil {
		return nil
	}
	out := new(ServerManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementStatus) DeepCopyInto(out *ServerManagementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementStatus.
func (in *ServerManagementStatus) DeepCopy() *ServerManagementStatus {
	if in == nil {
		return nil
	}
	out := new(ServerManagementStatus)
	in.DeepCopyInto(out)
	return out
}
