//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementConsoleSet) DeepCopyInto(out *ServerManagementConsoleSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementConsoleSet.
func (in *ServerManagementConsoleSet) DeepCopy() *ServerManagementConsoleSet {
	if in == nil {
		return nil
	}
	out := new(ServerManagementConsoleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerManagementConsoleSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementConsoleSetList) DeepCopyInto(out *ServerManagementConsoleSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerManagementConsoleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementConsoleSetList.
func (in *ServerManagementConsoleSetList) DeepCopy() *ServerManagementConsoleSetList {
	if in == nil {
		return nil
	}
	out := new(ServerManagementConsoleSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerManagementConsoleSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementConsoleSetSpec) DeepCopyInto(out *ServerManagementConsoleSetSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementConsoleSetSpec.
func (in *ServerManagementConsoleSetSpec) DeepCopy() *ServerManagementConsoleSetSpec {
	if in == nil {
		return nil
	}
	out := new(ServerManagementConsoleSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerManagementConsoleSetStatus) DeepCopyInto(out *ServerManagementConsoleSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerManagementConsoleSetStatus.
func (in *ServerManagementConsoleSetStatus) DeepCopy() *ServerManagementConsoleSetStatus {
	if in == nil {
		return nil
	}
	out := new(ServerManagementConsoleSetStatus)
	in.DeepCopyInto(out)
	return out
}
