//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselinesConfig) DeepCopyInto(out *BaselinesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselinesConfig.
func (in *BaselinesConfig) DeepCopy() *BaselinesConfig {
	if in == nil {
		return nil
	}
	out := new(BaselinesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateCatalog) DeepCopyInto(out *CreateCatalog) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(Repository)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateCatalog.
func (in *CreateCatalog) DeepCopy() *CreateCatalog {
	if in == nil {
		return nil
	}
	out := new(CreateCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DELLFirmwareUpdateOME) DeepCopyInto(out *DELLFirmwareUpdateOME) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DELLFirmwareUpdateOME.
func (in *DELLFirmwareUpdateOME) DeepCopy() *DELLFirmwareUpdateOME {
	if in == nil {
		return nil
	}
	out := new(DELLFirmwareUpdateOME)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DELLFirmwareUpdateOME) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DELLFirmwareUpdateOMEList) DeepCopyInto(out *DELLFirmwareUpdateOMEList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DELLFirmwareUpdateOME, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DELLFirmwareUpdateOMEList.
func (in *DELLFirmwareUpdateOMEList) DeepCopy() *DELLFirmwareUpdateOMEList {
	if in == nil {
		return nil
	}
	out := new(DELLFirmwareUpdateOMEList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DELLFirmwareUpdateOMEList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DELLFirmwareUpdateOMESpec) DeepCopyInto(out *DELLFirmwareUpdateOMESpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.CreateCatalog != nil {
		in, out := &in.CreateCatalog, &out.CreateCatalog
		*out = new(CreateCatalog)
		(*in).DeepCopyInto(*out)
	}
	if in.FirmwareUpgradeConfig != nil {
		in, out := &in.FirmwareUpgradeConfig, &out.FirmwareUpgradeConfig
		*out = new(FirmwareUpgradeConfig)
		**out = **in
	}
	if in.BaselineConfig != nil {
		in, out := &in.BaselineConfig, &out.BaselineConfig
		*out = new(BaselinesConfig)
		**out = **in
	}
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	if in.ServerMaintenanceRefs != nil {
		in, out := &in.ServerMaintenanceRefs, &out.ServerMaintenanceRefs
		*out = make([]apiv1alpha1.ServerMaintenanceRefItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DELLFirmwareUpdateOMESpec.
func (in *DELLFirmwareUpdateOMESpec) DeepCopy() *DELLFirmwareUpdateOMESpec {
	if in == nil {
		return nil
	}
	out := new(DELLFirmwareUpdateOMESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DELLFirmwareUpdateOMEStatus) DeepCopyInto(out *DELLFirmwareUpdateOMEStatus) {
	*out = *in
	if in.UpdateTask != nil {
		in, out := &in.UpdateTask, &out.UpdateTask
		*out = new(DellJob)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DELLFirmwareUpdateOMEStatus.
func (in *DELLFirmwareUpdateOMEStatus) DeepCopy() *DELLFirmwareUpdateOMEStatus {
	if in == nil {
		return nil
	}
	out := new(DELLFirmwareUpdateOMEStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellJob) DeepCopyInto(out *DellJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellJob.
func (in *DellJob) DeepCopy() *DellJob {
	if in == nil {
		return nil
	}
	out := new(DellJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpgradeConfig) DeepCopyInto(out *FirmwareUpgradeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpgradeConfig.
func (in *FirmwareUpgradeConfig) DeepCopy() *FirmwareUpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}
