//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUser) DeepCopyInto(out *BMCUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUser.
func (in *BMCUser) DeepCopy() *BMCUser {
	if in == nil {
		return nil
	}
	out := new(BMCUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserList) DeepCopyInto(out *BMCUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserList.
func (in *BMCUserList) DeepCopy() *BMCUserList {
	if in == nil {
		return nil
	}
	out := new(BMCUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSet) DeepCopyInto(out *BMCUserSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSet.
func (in *BMCUserSet) DeepCopy() *BMCUserSet {
	if in == nil {
		return nil
	}
	out := new(BMCUserSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUserSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSetList) DeepCopyInto(out *BMCUserSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCUserSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSetList.
func (in *BMCUserSetList) DeepCopy() *BMCUserSetList {
	if in == nil {
		return nil
	}
	out := new(BMCUserSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUserSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSetSpec) DeepCopyInto(out *BMCUserSetSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSetSpec.
func (in *BMCUserSetSpec) DeepCopy() *BMCUserSetSpec {
	if in == nil {
		return nil
	}
	out := new(BMCUserSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSetStatus) DeepCopyInto(out *BMCUserSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSetStatus.
func (in *BMCUserSetStatus) DeepCopy() *BMCUserSetStatus {
	if in == nil {
		return nil
	}
	out := new(BMCUserSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSetTemplate) DeepCopyInto(out *BMCUserSetTemplate) {
	*out = *in
	if in.RotationPeriod != nil {
		in, out := &in.RotationPeriod, &out.RotationPeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSetTemplate.
func (in *BMCUserSetTemplate) DeepCopy() *BMCUserSetTemplate {
	if in == nil {
		return nil
	}
	out := new(BMCUserSetTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSpec) DeepCopyInto(out *BMCUserSpec) {
	*out = *in
	if in.RotationPeriod != nil {
		in, out := &in.RotationPeriod, &out.RotationPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BMCSecretRef != nil {
		in, out := &in.BMCSecretRef, &out.BMCSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.BMCRef != nil {
		in, out := &in.BMCRef, &out.BMCRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSpec.
func (in *BMCUserSpec) DeepCopy() *BMCUserSpec {
	if in == nil {
		return nil
	}
	out := new(BMCUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserStatus) DeepCopyInto(out *BMCUserStatus) {
	*out = *in
	if in.EffectiveBMCSecretRef != nil {
		in, out := &in.EffectiveBMCSecretRef, &out.EffectiveBMCSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
	if in.PasswordExpiration != nil {
		in, out := &in.PasswordExpiration, &out.PasswordExpiration
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserStatus.
func (in *BMCUserStatus) DeepCopy() *BMCUserStatus {
	if in == nil {
		return nil
	}
	out := new(BMCUserStatus)
	in.DeepCopyInto(out)
	return out
}
