//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselinesConfig) DeepCopyInto(out *BaselinesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselinesConfig.
func (in *BaselinesConfig) DeepCopy() *BaselinesConfig {
	if in == nil {
		return nil
	}
	out := new(BaselinesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Console) DeepCopyInto(out *Console) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Console.
func (in *Console) DeepCopy() *Console {
	if in == nil {
		return nil
	}
	out := new(Console)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Console) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleList) DeepCopyInto(out *ConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Console, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleList.
func (in *ConsoleList) DeepCopy() *ConsoleList {
	if in == nil {
		return nil
	}
	out := new(ConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleSpec) DeepCopyInto(out *ConsoleSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	out.BMCCredentialSecretRef = in.BMCCredentialSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleSpec.
func (in *ConsoleSpec) DeepCopy() *ConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleStatus) DeepCopyInto(out *ConsoleStatus) {
	*out = *in
	if in.PendingOperations != nil {
		in, out := &in.PendingOperations, &out.PendingOperations
		*out = make([]PendingOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleStatus.
func (in *ConsoleStatus) DeepCopy() *ConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(ConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateCatalog) DeepCopyInto(out *CreateCatalog) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(Repository)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateCatalog.
func (in *CreateCatalog) DeepCopy() *CreateCatalog {
	if in == nil {
		return nil
	}
	out := new(CreateCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellBaseline) DeepCopyInto(out *DellBaseline) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellBaseline.
func (in *DellBaseline) DeepCopy() *DellBaseline {
	if in == nil {
		return nil
	}
	out := new(DellBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellCatalog) DeepCopyInto(out *DellCatalog) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellCatalog.
func (in *DellCatalog) DeepCopy() *DellCatalog {
	if in == nil {
		return nil
	}
	out := new(DellCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DellJob) DeepCopyInto(out *DellJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DellJob.
func (in *DellJob) DeepCopy() *DellJob {
	if in == nil {
		return nil
	}
	out := new(DellJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDELL) DeepCopyInto(out *FirmwareUpdateDELL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDELL.
func (in *FirmwareUpdateDELL) DeepCopy() *FirmwareUpdateDELL {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDELL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateDELL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDELLList) DeepCopyInto(out *FirmwareUpdateDELLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirmwareUpdateDELL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDELLList.
func (in *FirmwareUpdateDELLList) DeepCopy() *FirmwareUpdateDELLList {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDELLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateDELLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDELLSpec) DeepCopyInto(out *FirmwareUpdateDELLSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.CreateCatalog != nil {
		in, out := &in.CreateCatalog, &out.CreateCatalog
		*out = new(CreateCatalog)
		(*in).DeepCopyInto(*out)
	}
	if in.FirmwareUpgradeConfig != nil {
		in, out := &in.FirmwareUpgradeConfig, &out.FirmwareUpgradeConfig
		*out = new(FirmwareUpgradeConfig)
		**out = **in
	}
	if in.BaselineConfig != nil {
		in, out := &in.BaselineConfig, &out.BaselineConfig
		*out = new(BaselinesConfig)
		**out = **in
	}
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	if in.ServerMaintenanceRefs != nil {
		in, out := &in.ServerMaintenanceRefs, &out.ServerMaintenanceRefs
		*out = make([]apiv1alpha1.ServerMaintenanceRefItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDELLSpec.
func (in *FirmwareUpdateDELLSpec) DeepCopy() *FirmwareUpdateDELLSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDELLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDELLStatus) DeepCopyInto(out *FirmwareUpdateDELLStatus) {
	*out = *in
	if in.UpdateTask != nil {
		in, out := &in.UpdateTask, &out.UpdateTask
		*out = new(DellJob)
		**out = **in
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(DellCatalog)
		**out = **in
	}
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(DellBaseline)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDELLStatus.
func (in *FirmwareUpdateDELLStatus) DeepCopy() *FirmwareUpdateDELLStatus {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDELLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpgradeConfig) DeepCopyInto(out *FirmwareUpgradeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpgradeConfig.
func (in *FirmwareUpgradeConfig) DeepCopy() *FirmwareUpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingOperation) DeepCopyInto(out *PendingOperation) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastChecked.DeepCopyInto(&out.LastChecked)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingOperation.
func (in *PendingOperation) DeepCopy() *PendingOperation {
	if in == nil {
		return nil
	}
	out := new(PendingOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}
