//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompliancePolicySpec) DeepCopyInto(out *CompliancePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompliancePolicySpec.
func (in *CompliancePolicySpec) DeepCopy() *CompliancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(CompliancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Console) DeepCopyInto(out *Console) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Console.
func (in *Console) DeepCopy() *Console {
	if in == nil {
		return nil
	}
	out := new(Console)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Console) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleList) DeepCopyInto(out *ConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Console, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleList.
func (in *ConsoleList) DeepCopy() *ConsoleList {
	if in == nil {
		return nil
	}
	out := new(ConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleSpec) DeepCopyInto(out *ConsoleSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	out.BMCCredentialSecretRef = in.BMCCredentialSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleSpec.
func (in *ConsoleSpec) DeepCopy() *ConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleStatus) DeepCopyInto(out *ConsoleStatus) {
	*out = *in
	if in.PendingOperations != nil {
		in, out := &in.PendingOperations, &out.PendingOperations
		*out = make([]PendingOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleStatus.
func (in *ConsoleStatus) DeepCopy() *ConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(ConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwarePayload) DeepCopyInto(out *FirmwarePayload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwarePayload.
func (in *FirmwarePayload) DeepCopy() *FirmwarePayload {
	if in == nil {
		return nil
	}
	out := new(FirmwarePayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateLenovo) DeepCopyInto(out *FirmwareUpdateLenovo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateLenovo.
func (in *FirmwareUpdateLenovo) DeepCopy() *FirmwareUpdateLenovo {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateLenovo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateLenovo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateLenovoList) DeepCopyInto(out *FirmwareUpdateLenovoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirmwareUpdateLenovo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateLenovoList.
func (in *FirmwareUpdateLenovoList) DeepCopy() *FirmwareUpdateLenovoList {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateLenovoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateLenovoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateLenovoSpec) DeepCopyInto(out *FirmwareUpdateLenovoSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	out.FirmwarePayload = in.FirmwarePayload
	out.CompliancePolicy = in.CompliancePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateLenovoSpec.
func (in *FirmwareUpdateLenovoSpec) DeepCopy() *FirmwareUpdateLenovoSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateLenovoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateLenovoStatus) DeepCopyInto(out *FirmwareUpdateLenovoStatus) {
	*out = *in
	if in.MaintenanceRefs != nil {
		in, out := &in.MaintenanceRefs, &out.MaintenanceRefs
		*out = make([]MaintenanceRef, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateLenovoStatus.
func (in *FirmwareUpdateLenovoStatus) DeepCopy() *FirmwareUpdateLenovoStatus {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateLenovoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceRef) DeepCopyInto(out *MaintenanceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceRef.
func (in *MaintenanceRef) DeepCopy() *MaintenanceRef {
	if in == nil {
		return nil
	}
	out := new(MaintenanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingOperation) DeepCopyInto(out *PendingOperation) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastChecked.DeepCopyInto(&out.LastChecked)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingOperation.
func (in *PendingOperation) DeepCopy() *PendingOperation {
	if in == nil {
		return nil
	}
	out := new(PendingOperation)
	in.DeepCopyInto(out)
	return out
}
